apiVersion: apps/v1
kind: Deployment
metadata:
  name: subtoken-depl
  labels:
    app: subtoken
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subtoken
  template:
    metadata:
      labels:
        app: subtoken
    spec:
      containers:
        - name: subtoken
          image: qualla/blockchain-subtoken:latest
          ports:
            - containerPort: 4003
          env:
            - name: PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: server-secret
                  key: PRIVATE_KEY
            - name: PRIVATE_KEY2
              valueFrom:
                secretKeyRef:
                  name: server-secret
                  key: PRIVATE_KEY2
            - name: ACCOUNT
              valueFrom:
                secretKeyRef:
                  name: server-secret
                  key: ACCOUNT
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: server-secret
                  key: RABBITMQ_DEFAULT_USER
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: server-secret
                  key: RABBITMQ_DEFAULT_PASS
            - name: NETWORK_ID
              valueFrom:
                configMapKeyRef:
                  name: server-configmap
                  key: NETWORK_ID
            - name: NETWORK_URI
              valueFrom:
                configMapKeyRef:
                  name: server-configmap
                  key: NETWORK_URI
            - name: GRAPH_URI
              valueFrom:
                configMapKeyRef:
                  name: server-configmap
                  key: GRAPH_URI
            - name: DAI_CONTRACT
              valueFrom:
                configMapKeyRef:
                  name: server-configmap
                  key: DAI_CONTRACT
            - name: SUB_CONTRACT
              valueFrom:
                configMapKeyRef:
                  name: server-configmap
                  key: SUB_CONTRACT
            - name: RABBITMQ_SERVER
              valueFrom:
                configMapKeyRef:
                  name: server-configmap
                  key: RABBITMQ_SERVER
---
apiVersion: v1
kind: Service
metadata:
  name: subtoken-service
spec:
  selector:
    app: subtoken
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 4003
      targetPort: 4003