apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qualla-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - api.qualla.io
    secretName: qualla-tls
  rules:
    - host: api.qualla.io
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: gateway
              port:
                number: 4000
